---
hide_body: false
fields:
- name: Description
  label: Description
  type: text
  hidden: false
  default: ''
- name: Tags
  label: Tags
  type: list
  hidden: false
  default: []
- name: Categories
  label: Categories
  type: list
  hidden: false
  default: []
