---
pages:
- index2.md
hide_body: false
fields:
- name: Description
  label: Description
  type: text
  hidden: false
  default: ''
- name: Tags
  label: Tags
  type: list
  hidden: false
  default: []
- name: Categories
  label: Categories
  type: list
  hidden: false
  default: []
- type: file
  default: "/img/unfinished_lanterns_small-34.jpg"
- type: image_gallery
  label: Products
  name: products
  description: List of product images for display
  default:
  - "/img/Green_Lantern_12_x11_x11.jpg"
  - "/img/Ken's_Lantern_16_x9_x9.jpg"
  - "/img/Tall_Indigo_Lantern_Stoneware_21_x8_x8.jpg"
- type: field_group_list
  label: row group with 3 items
  hidden: false
  fields:
  - type: file
  - type: file
  - type: file
  name: row_group_with_3_items
  description: Row with three items
- type: field_group_list
  name: galary_rows
  label: galary rows
  fields:
  - type: image_gallery
    name: multi_item_gallary
    label: Multi item gallary
